USE URSafeApp;
GO

IF COL_LENGTH('Users', 'Department') IS NULL
BEGIN
  ALTER TABLE Users ADD Department NVARCHAR(100) NULL;
END
GO

IF COL_LENGTH('Users', 'IsActive') IS NULL
BEGIN
  ALTER TABLE Users ADD IsActive BIT NOT NULL CONSTRAINT DF_Users_IsActive DEFAULT 1;
END
GO

IF COL_LENGTH('Users', 'UpdatedAt') IS NULL
BEGIN
  ALTER TABLE Users ADD UpdatedAt DATETIME2 NULL;
END
GO

UPDATE Users
SET UpdatedAt = CreatedAt
WHERE UpdatedAt IS NULL;
GO
