FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json ./
COPY apps ./apps
COPY packages ./packages
COPY services ./services
COPY tsconfig.base.json ./
RUN npm install

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app /app
ARG APP_NAME
RUN npm run build -w ${APP_NAME}

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app /app
ARG APP_NAME
CMD ["sh", "-c", "npm run start -w ${APP_NAME}"]
